name: EndsWhenOnePersonDies
version: '1.0-Remo'
main: jp.klneg.dev.endsWhenOnePersonDies.EndsWhenOnePersonDies
api-version: '1.21'
authors: [ Cyrus ]
depend:
  - NoteBlockAPI
description: HardCore automatic progression
commands:
  deathpointtp:
    description: DeathPointTeleportCommands.
    aliases:
      - dptp

  deathcount:
    description: CheckPlayerDeathCount
    aliases:
      - dc

  glow:
    description: I'm Star!
    aliases:
      - g